define

    name sub attribute,
      value string;
    started-at sub attribute,
      value datetime;
    duration sub attribute,
      value long;
    first-name sub attribute,
      value string;
    last-name sub attribute,
      value string;
    phone-number sub attribute,
      value string,
      plays in-use:account;
    city sub attribute,
      value string;
    age sub attribute,
      value long;
    nick-name sub attribute,
      value string;
    twitter-username sub attribute,
      value string;
    fakebook-link sub attribute,
      value string;
    call-rating sub attribute,
      value long;

    contract sub relation,
        relates provider,
        relates customer;

    call sub relation,
        relates caller,
        relates callee,
        owns started-at,
        owns duration,
        owns call-rating,
        plays communication-channel:past-call;

    communication-channel sub relation,
        relates peer,
        relates past-call;

    company sub entity,
        plays contract:provider,
        owns name @key;

    person sub entity,
        plays contract:customer,
        plays call:caller,
        plays call:callee,
        owns first-name,
        owns last-name,
        owns phone-number @key,
        owns city,
        owns age,
        owns nick-name,
        owns twitter-username,
        owns fakebook-link,
        plays communication-channel:peer;

    is-in-use sub attribute, value string,
        plays in-use:status;

    in-use sub relation,
        relates status,
        relates account;
