define

text sub entity,
    owns uid @key,
    plays tag:tagged;
uid sub attribute, value long;

label sub entity,
    owns name @key,
    plays tag:tagger;
name sub attribute, value string;

tag sub relation,
    relates tagger,
    relates tagged;